openapi: 3.0.0
info:
  title: Node React Backend
  description: Nodejs boilerplate with todo
  version: 0.0.1

paths:
  /todos:
    get:
      description: Returns a list of todos
      responses:
        '200':
          description: A JSON array of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
  /todos/{todoId}:
    get:
      description: Returns a todo by ID
      parameters:
        - name: todoId
          in: path
          required: true
          description: Todo ID
          schema:
            type: string
      responses:
        '200':
          description: A todo object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        '400':
          description: ID is invalid
        '404':
          description: Todo with ID not found

components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: abc123
        name:
          type: string
          example: Buy Milk
